# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a8223b8efb4bd5e70e5097a298c028cfaeb12b161236d2e13fe34e8562b5a0a017afa980c48b22ad1f4c394da6293a5c5ee835b88141ff9e04a6a4165609ca8

test:
  secret_key_base: 6bcaa7c13a122589edc4d6b70ef411151f8bf9d13489a542f4babc8a657ab0a78f7699b9658c191e51afbb6aef86c615e5bd4bf6f1552c462c03e5c74f7d4d74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
